//Generated by gRPC Go plugin
//If you make any local changes, they will be lost
//source: cchat

package call

import "github.com/google/flatbuffers/go"

import (
  context "context"
  grpc "google.golang.org/grpc"
)

// Client API for Canceller service
type CancellerClient interface{
  Cancel(ctx context.Context, in *flatbuffers.Builder, 
  	opts... grpc.CallOption) (* Error, error)  
}

type cancellerClient struct {
  cc *grpc.ClientConn
}

func NewCancellerClient(cc *grpc.ClientConn) CancellerClient {
  return &cancellerClient{cc}
}

func (c *cancellerClient) Cancel(ctx context.Context, in *flatbuffers.Builder, 
	opts... grpc.CallOption) (* Error, error) {
  out := new(Error)
  err := grpc.Invoke(ctx, "/cchat.call.Canceller/Cancel", in, out, c.cc, opts...)
  if err != nil { return nil, err }
  return out, nil
}

// Server API for Canceller service
type CancellerServer interface {
  Cancel(context.Context, *Context) (*flatbuffers.Builder, error)  
}

func RegisterCancellerServer(s *grpc.Server, srv CancellerServer) {
  s.RegisterService(&_Canceller_serviceDesc, srv)
}

func _Canceller_Cancel_Handler(srv interface{}, ctx context.Context,
	dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
  in := new(Context)
  if err := dec(in); err != nil { return nil, err }
  if interceptor == nil { return srv.(CancellerServer).Cancel(ctx, in) }
  info := &grpc.UnaryServerInfo{
    Server: srv,
    FullMethod: "/cchat.call.Canceller/Cancel",
  }
  
  handler := func(ctx context.Context, req interface{}) (interface{}, error) {
    return srv.(CancellerServer).Cancel(ctx, req.(* Context))
  }
  return interceptor(ctx, in, info, handler)
}


var _Canceller_serviceDesc = grpc.ServiceDesc{
  ServiceName: "cchat.call.Canceller",
  HandlerType: (*CancellerServer)(nil),
  Methods: []grpc.MethodDesc{
    {
      MethodName: "Cancel",
      Handler: _Canceller_Cancel_Handler, 
    },
  },
  Streams: []grpc.StreamDesc{
  },
}

