// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package call

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type StopHandle struct {
	_tab flatbuffers.Table
}

func GetRootAsStopHandle(buf []byte, offset flatbuffers.UOffsetT) *StopHandle {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StopHandle{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsStopHandle(buf []byte, offset flatbuffers.UOffsetT) *StopHandle {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StopHandle{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *StopHandle) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StopHandle) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StopHandle) StopId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StopHandle) MutateStopId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func StopHandleStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func StopHandleAddStopId(builder *flatbuffers.Builder, stopId uint64) {
	builder.PrependUint64Slot(0, stopId, 0)
}
func StopHandleEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
