// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cchat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Actioner struct {
	_tab flatbuffers.Table
}

func GetRootAsActioner(buf []byte, offset flatbuffers.UOffsetT) *Actioner {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Actioner{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsActioner(buf []byte, offset flatbuffers.UOffsetT) *Actioner {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Actioner{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *Actioner) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Actioner) Table() flatbuffers.Table {
	return rcv._tab
}

func ActionerStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func ActionerEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
