// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cchat

import (
	flatbuffers "github.com/google/flatbuffers/go"

	cchat__call "cchat/call"
)

type AddTyperParameters struct {
	_tab flatbuffers.Table
}

func GetRootAsAddTyperParameters(buf []byte, offset flatbuffers.UOffsetT) *AddTyperParameters {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AddTyperParameters{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsAddTyperParameters(buf []byte, offset flatbuffers.UOffsetT) *AddTyperParameters {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &AddTyperParameters{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *AddTyperParameters) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AddTyperParameters) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AddTyperParameters) Call(obj *cchat__call.ID) *cchat__call.ID {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(cchat__call.ID)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *AddTyperParameters) Typer(obj *Typer) *Typer {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Typer)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func AddTyperParametersStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func AddTyperParametersAddCall(builder *flatbuffers.Builder, call flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(call), 0)
}
func AddTyperParametersAddTyper(builder *flatbuffers.Builder, typer flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(typer), 0)
}
func AddTyperParametersEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
