// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cchat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Attacher struct {
	_tab flatbuffers.Table
}

func GetRootAsAttacher(buf []byte, offset flatbuffers.UOffsetT) *Attacher {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Attacher{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsAttacher(buf []byte, offset flatbuffers.UOffsetT) *Attacher {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Attacher{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *Attacher) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Attacher) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Attacher) Attachments(obj *MessageAttachment, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *Attacher) AttachmentsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func AttacherStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func AttacherAddAttachments(builder *flatbuffers.Builder, attachments flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(attachments), 0)
}
func AttacherStartAttachmentsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func AttacherEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
