//Generated by gRPC Go plugin
//If you make any local changes, they will be lost
//source: cchat

package cchat

import "github.com/google/flatbuffers/go"

import (
  context "context"
  grpc "google.golang.org/grpc"
)

// Client API for AuthenticatorService service
type AuthenticatorServiceClient interface{
  Authenticate(ctx context.Context, in *flatbuffers.Builder, 
  	opts... grpc.CallOption) (* AuthenticateReturns, error)  
}

type authenticatorServiceClient struct {
  cc *grpc.ClientConn
}

func NewAuthenticatorServiceClient(cc *grpc.ClientConn) AuthenticatorServiceClient {
  return &authenticatorServiceClient{cc}
}

func (c *authenticatorServiceClient) Authenticate(ctx context.Context, in *flatbuffers.Builder, 
	opts... grpc.CallOption) (* AuthenticateReturns, error) {
  out := new(AuthenticateReturns)
  err := grpc.Invoke(ctx, "/cchat.AuthenticatorService/Authenticate", in, out, c.cc, opts...)
  if err != nil { return nil, err }
  return out, nil
}

// Server API for AuthenticatorService service
type AuthenticatorServiceServer interface {
  Authenticate(context.Context, *AuthenticateParameters) (*flatbuffers.Builder, error)  
}

func RegisterAuthenticatorServiceServer(s *grpc.Server, srv AuthenticatorServiceServer) {
  s.RegisterService(&_AuthenticatorService_serviceDesc, srv)
}

func _AuthenticatorService_Authenticate_Handler(srv interface{}, ctx context.Context,
	dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
  in := new(AuthenticateParameters)
  if err := dec(in); err != nil { return nil, err }
  if interceptor == nil { return srv.(AuthenticatorServiceServer).Authenticate(ctx, in) }
  info := &grpc.UnaryServerInfo{
    Server: srv,
    FullMethod: "/cchat.AuthenticatorService/Authenticate",
  }
  
  handler := func(ctx context.Context, req interface{}) (interface{}, error) {
    return srv.(AuthenticatorServiceServer).Authenticate(ctx, req.(* AuthenticateParameters))
  }
  return interceptor(ctx, in, info, handler)
}


var _AuthenticatorService_serviceDesc = grpc.ServiceDesc{
  ServiceName: "cchat.AuthenticatorService",
  HandlerType: (*AuthenticatorServiceServer)(nil),
  Methods: []grpc.MethodDesc{
    {
      MethodName: "Authenticate",
      Handler: _AuthenticatorService_Authenticate_Handler, 
    },
  },
  Streams: []grpc.StreamDesc{
  },
}

