// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cchat

import (
	flatbuffers "github.com/google/flatbuffers/go"

	cchat__call "cchat/call"
)

type AuthenticateParameters struct {
	_tab flatbuffers.Table
}

func GetRootAsAuthenticateParameters(buf []byte, offset flatbuffers.UOffsetT) *AuthenticateParameters {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AuthenticateParameters{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsAuthenticateParameters(buf []byte, offset flatbuffers.UOffsetT) *AuthenticateParameters {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &AuthenticateParameters{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *AuthenticateParameters) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AuthenticateParameters) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AuthenticateParameters) Call(obj *cchat__call.ID) *cchat__call.ID {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(cchat__call.ID)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *AuthenticateParameters) StringArray(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *AuthenticateParameters) StringArrayLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func AuthenticateParametersStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func AuthenticateParametersAddCall(builder *flatbuffers.Builder, call flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(call), 0)
}
func AuthenticateParametersAddStringArray(builder *flatbuffers.Builder, stringArray flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(stringArray), 0)
}
func AuthenticateParametersStartStringArrayVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func AuthenticateParametersEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
