// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cchat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AuthenticateError struct {
	_tab flatbuffers.Table
}

func GetRootAsAuthenticateError(buf []byte, offset flatbuffers.UOffsetT) *AuthenticateError {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AuthenticateError{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsAuthenticateError(buf []byte, offset flatbuffers.UOffsetT) *AuthenticateError {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &AuthenticateError{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *AuthenticateError) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AuthenticateError) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AuthenticateError) Err() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *AuthenticateError) NextStage(obj *Authenticator, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *AuthenticateError) NextStageLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func AuthenticateErrorStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func AuthenticateErrorAddErr(builder *flatbuffers.Builder, err flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(err), 0)
}
func AuthenticateErrorAddNextStage(builder *flatbuffers.Builder, nextStage flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(nextStage), 0)
}
func AuthenticateErrorStartNextStageVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func AuthenticateErrorEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
