// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cchat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Backlogger struct {
	_tab flatbuffers.Table
}

func GetRootAsBacklogger(buf []byte, offset flatbuffers.UOffsetT) *Backlogger {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Backlogger{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsBacklogger(buf []byte, offset flatbuffers.UOffsetT) *Backlogger {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Backlogger{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *Backlogger) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Backlogger) Table() flatbuffers.Table {
	return rcv._tab
}

func BackloggerStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func BackloggerEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
