// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cchat

import (
	flatbuffers "github.com/google/flatbuffers/go"

	cchat__call "cchat/call"
)

type BacklogParameters struct {
	_tab flatbuffers.Table
}

func GetRootAsBacklogParameters(buf []byte, offset flatbuffers.UOffsetT) *BacklogParameters {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &BacklogParameters{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsBacklogParameters(buf []byte, offset flatbuffers.UOffsetT) *BacklogParameters {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &BacklogParameters{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *BacklogParameters) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *BacklogParameters) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *BacklogParameters) Call(obj *cchat__call.ID) *cchat__call.ID {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(cchat__call.ID)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *BacklogParameters) Ctx(obj *cchat__call.Context) *cchat__call.Context {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(cchat__call.Context)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *BacklogParameters) Before() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *BacklogParameters) Msgc(obj *MessagesContainer) *MessagesContainer {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(MessagesContainer)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func BacklogParametersStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func BacklogParametersAddCall(builder *flatbuffers.Builder, call flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(call), 0)
}
func BacklogParametersAddCtx(builder *flatbuffers.Builder, ctx flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(ctx), 0)
}
func BacklogParametersAddBefore(builder *flatbuffers.Builder, before flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(before), 0)
}
func BacklogParametersAddMsgc(builder *flatbuffers.Builder, msgc flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(msgc), 0)
}
func BacklogParametersEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
