// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cchat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Commander struct {
	_tab flatbuffers.Table
}

func GetRootAsCommander(buf []byte, offset flatbuffers.UOffsetT) *Commander {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Commander{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsCommander(buf []byte, offset flatbuffers.UOffsetT) *Commander {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Commander{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *Commander) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Commander) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Commander) Completer(obj *Completer) *Completer {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Completer)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func CommanderStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func CommanderAddCompleter(builder *flatbuffers.Builder, completer flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(completer), 0)
}
func CommanderEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
