//Generated by gRPC Go plugin
//If you make any local changes, they will be lost
//source: cchat

package cchat

import "github.com/google/flatbuffers/go"

import (
  context "context"
  grpc "google.golang.org/grpc"
)

// Client API for CompleterService service
type CompleterServiceClient interface{
  Complete(ctx context.Context, in *flatbuffers.Builder, 
  	opts... grpc.CallOption) (* CompleteReturns, error)  
}

type completerServiceClient struct {
  cc *grpc.ClientConn
}

func NewCompleterServiceClient(cc *grpc.ClientConn) CompleterServiceClient {
  return &completerServiceClient{cc}
}

func (c *completerServiceClient) Complete(ctx context.Context, in *flatbuffers.Builder, 
	opts... grpc.CallOption) (* CompleteReturns, error) {
  out := new(CompleteReturns)
  err := grpc.Invoke(ctx, "/cchat.CompleterService/Complete", in, out, c.cc, opts...)
  if err != nil { return nil, err }
  return out, nil
}

// Server API for CompleterService service
type CompleterServiceServer interface {
  Complete(context.Context, *CompleteParameters) (*flatbuffers.Builder, error)  
}

func RegisterCompleterServiceServer(s *grpc.Server, srv CompleterServiceServer) {
  s.RegisterService(&_CompleterService_serviceDesc, srv)
}

func _CompleterService_Complete_Handler(srv interface{}, ctx context.Context,
	dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
  in := new(CompleteParameters)
  if err := dec(in); err != nil { return nil, err }
  if interceptor == nil { return srv.(CompleterServiceServer).Complete(ctx, in) }
  info := &grpc.UnaryServerInfo{
    Server: srv,
    FullMethod: "/cchat.CompleterService/Complete",
  }
  
  handler := func(ctx context.Context, req interface{}) (interface{}, error) {
    return srv.(CompleterServiceServer).Complete(ctx, req.(* CompleteParameters))
  }
  return interceptor(ctx, in, info, handler)
}


var _CompleterService_serviceDesc = grpc.ServiceDesc{
  ServiceName: "cchat.CompleterService",
  HandlerType: (*CompleterServiceServer)(nil),
  Methods: []grpc.MethodDesc{
    {
      MethodName: "Complete",
      Handler: _CompleterService_Complete_Handler, 
    },
  },
  Streams: []grpc.StreamDesc{
  },
}

