// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cchat

import (
	flatbuffers "github.com/google/flatbuffers/go"

	cchat__call "cchat/call"
)

type CompleteReturns struct {
	_tab flatbuffers.Table
}

func GetRootAsCompleteReturns(buf []byte, offset flatbuffers.UOffsetT) *CompleteReturns {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CompleteReturns{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsCompleteReturns(buf []byte, offset flatbuffers.UOffsetT) *CompleteReturns {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &CompleteReturns{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *CompleteReturns) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CompleteReturns) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CompleteReturns) Call(obj *cchat__call.ID) *cchat__call.ID {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(cchat__call.ID)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func CompleteReturnsStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func CompleteReturnsAddCall(builder *flatbuffers.Builder, call flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(call), 0)
}
func CompleteReturnsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
