// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cchat

import (
	flatbuffers "github.com/google/flatbuffers/go"

	cchat__call "cchat/call"
)

type CreateMessageParameters struct {
	_tab flatbuffers.Table
}

func GetRootAsCreateMessageParameters(buf []byte, offset flatbuffers.UOffsetT) *CreateMessageParameters {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CreateMessageParameters{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsCreateMessageParameters(buf []byte, offset flatbuffers.UOffsetT) *CreateMessageParameters {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &CreateMessageParameters{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *CreateMessageParameters) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CreateMessageParameters) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CreateMessageParameters) Call(obj *cchat__call.ID) *cchat__call.ID {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(cchat__call.ID)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *CreateMessageParameters) MessageCreate(obj *MessageCreate) *MessageCreate {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(MessageCreate)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func CreateMessageParametersStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func CreateMessageParametersAddCall(builder *flatbuffers.Builder, call flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(call), 0)
}
func CreateMessageParametersAddMessageCreate(builder *flatbuffers.Builder, messageCreate flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(messageCreate), 0)
}
func CreateMessageParametersEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
