// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cchat

import (
	flatbuffers "github.com/google/flatbuffers/go"

	cchat__call "cchat/call"
)

type DeleteMessageParameters struct {
	_tab flatbuffers.Table
}

func GetRootAsDeleteMessageParameters(buf []byte, offset flatbuffers.UOffsetT) *DeleteMessageParameters {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DeleteMessageParameters{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsDeleteMessageParameters(buf []byte, offset flatbuffers.UOffsetT) *DeleteMessageParameters {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &DeleteMessageParameters{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *DeleteMessageParameters) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DeleteMessageParameters) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DeleteMessageParameters) Call(obj *cchat__call.ID) *cchat__call.ID {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(cchat__call.ID)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *DeleteMessageParameters) MessageDelete(obj *MessageDelete) *MessageDelete {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(MessageDelete)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func DeleteMessageParametersStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func DeleteMessageParametersAddCall(builder *flatbuffers.Builder, call flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(call), 0)
}
func DeleteMessageParametersAddMessageDelete(builder *flatbuffers.Builder, messageDelete flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(messageDelete), 0)
}
func DeleteMessageParametersEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
