// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cchat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Editor struct {
	_tab flatbuffers.Table
}

func GetRootAsEditor(buf []byte, offset flatbuffers.UOffsetT) *Editor {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Editor{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsEditor(buf []byte, offset flatbuffers.UOffsetT) *Editor {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Editor{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *Editor) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Editor) Table() flatbuffers.Table {
	return rcv._tab
}

func EditorStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func EditorEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
