// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cchat

import (
	flatbuffers "github.com/google/flatbuffers/go"

	cchat__core "cchat/core"
)

type ErrInvalidConfigAtField struct {
	_tab flatbuffers.Table
}

func GetRootAsErrInvalidConfigAtField(buf []byte, offset flatbuffers.UOffsetT) *ErrInvalidConfigAtField {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ErrInvalidConfigAtField{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsErrInvalidConfigAtField(buf []byte, offset flatbuffers.UOffsetT) *ErrInvalidConfigAtField {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ErrInvalidConfigAtField{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *ErrInvalidConfigAtField) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ErrInvalidConfigAtField) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ErrInvalidConfigAtField) Key() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ErrInvalidConfigAtField) Err(obj *cchat__core.Error) *cchat__core.Error {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(cchat__core.Error)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func ErrInvalidConfigAtFieldStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ErrInvalidConfigAtFieldAddKey(builder *flatbuffers.Builder, key flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(key), 0)
}
func ErrInvalidConfigAtFieldAddErr(builder *flatbuffers.Builder, err flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(err), 0)
}
func ErrInvalidConfigAtFieldEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
