// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cchat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type IconContainer struct {
	_tab flatbuffers.Table
}

func GetRootAsIconContainer(buf []byte, offset flatbuffers.UOffsetT) *IconContainer {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &IconContainer{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsIconContainer(buf []byte, offset flatbuffers.UOffsetT) *IconContainer {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &IconContainer{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *IconContainer) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *IconContainer) Table() flatbuffers.Table {
	return rcv._tab
}

func IconContainerStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func IconContainerEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
