// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cchat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ImageContainer struct {
	_tab flatbuffers.Table
}

func GetRootAsImageContainer(buf []byte, offset flatbuffers.UOffsetT) *ImageContainer {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ImageContainer{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsImageContainer(buf []byte, offset flatbuffers.UOffsetT) *ImageContainer {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ImageContainer{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *ImageContainer) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ImageContainer) Table() flatbuffers.Table {
	return rcv._tab
}

func ImageContainerStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func ImageContainerEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
