//Generated by gRPC Go plugin
//If you make any local changes, they will be lost
//source: cchat

package cchat

import "github.com/google/flatbuffers/go"

import (
  context "context"
  grpc "google.golang.org/grpc"
)

// Client API for ImageContainerService service
type ImageContainerServiceClient interface{
  SetImage(ctx context.Context, in *flatbuffers.Builder, 
  	opts... grpc.CallOption) (* NoReply, error)  
}

type imageContainerServiceClient struct {
  cc *grpc.ClientConn
}

func NewImageContainerServiceClient(cc *grpc.ClientConn) ImageContainerServiceClient {
  return &imageContainerServiceClient{cc}
}

func (c *imageContainerServiceClient) SetImage(ctx context.Context, in *flatbuffers.Builder, 
	opts... grpc.CallOption) (* NoReply, error) {
  out := new(NoReply)
  err := grpc.Invoke(ctx, "/cchat.ImageContainerService/SetImage", in, out, c.cc, opts...)
  if err != nil { return nil, err }
  return out, nil
}

// Server API for ImageContainerService service
type ImageContainerServiceServer interface {
  SetImage(context.Context, *SetImageParameters) (*flatbuffers.Builder, error)  
}

func RegisterImageContainerServiceServer(s *grpc.Server, srv ImageContainerServiceServer) {
  s.RegisterService(&_ImageContainerService_serviceDesc, srv)
}

func _ImageContainerService_SetImage_Handler(srv interface{}, ctx context.Context,
	dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
  in := new(SetImageParameters)
  if err := dec(in); err != nil { return nil, err }
  if interceptor == nil { return srv.(ImageContainerServiceServer).SetImage(ctx, in) }
  info := &grpc.UnaryServerInfo{
    Server: srv,
    FullMethod: "/cchat.ImageContainerService/SetImage",
  }
  
  handler := func(ctx context.Context, req interface{}) (interface{}, error) {
    return srv.(ImageContainerServiceServer).SetImage(ctx, req.(* SetImageParameters))
  }
  return interceptor(ctx, in, info, handler)
}


var _ImageContainerService_serviceDesc = grpc.ServiceDesc{
  ServiceName: "cchat.ImageContainerService",
  HandlerType: (*ImageContainerServiceServer)(nil),
  Methods: []grpc.MethodDesc{
    {
      MethodName: "SetImage",
      Handler: _ImageContainerService_SetImage_Handler, 
    },
  },
  Streams: []grpc.StreamDesc{
  },
}

