// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cchat

import (
	flatbuffers "github.com/google/flatbuffers/go"

	cchat__call "cchat/call"
)

type IsEditableParameters struct {
	_tab flatbuffers.Table
}

func GetRootAsIsEditableParameters(buf []byte, offset flatbuffers.UOffsetT) *IsEditableParameters {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &IsEditableParameters{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsIsEditableParameters(buf []byte, offset flatbuffers.UOffsetT) *IsEditableParameters {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &IsEditableParameters{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *IsEditableParameters) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *IsEditableParameters) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *IsEditableParameters) Call(obj *cchat__call.ID) *cchat__call.ID {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(cchat__call.ID)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *IsEditableParameters) Id() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func IsEditableParametersStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func IsEditableParametersAddCall(builder *flatbuffers.Builder, call flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(call), 0)
}
func IsEditableParametersAddId(builder *flatbuffers.Builder, id flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(id), 0)
}
func IsEditableParametersEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
