// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cchat

import (
	flatbuffers "github.com/google/flatbuffers/go"

	cchat__call "cchat/call"
)

type JoinServerParameters struct {
	_tab flatbuffers.Table
}

func GetRootAsJoinServerParameters(buf []byte, offset flatbuffers.UOffsetT) *JoinServerParameters {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &JoinServerParameters{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsJoinServerParameters(buf []byte, offset flatbuffers.UOffsetT) *JoinServerParameters {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &JoinServerParameters{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *JoinServerParameters) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *JoinServerParameters) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *JoinServerParameters) Call(obj *cchat__call.ID) *cchat__call.ID {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(cchat__call.ID)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *JoinServerParameters) Ctx(obj *cchat__call.Context) *cchat__call.Context {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(cchat__call.Context)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *JoinServerParameters) MessagesContainer(obj *MessagesContainer) *MessagesContainer {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(MessagesContainer)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func JoinServerParametersStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func JoinServerParametersAddCall(builder *flatbuffers.Builder, call flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(call), 0)
}
func JoinServerParametersAddCtx(builder *flatbuffers.Builder, ctx flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(ctx), 0)
}
func JoinServerParametersAddMessagesContainer(builder *flatbuffers.Builder, messagesContainer flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(messagesContainer), 0)
}
func JoinServerParametersEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
