//Generated by gRPC Go plugin
//If you make any local changes, they will be lost
//source: cchat

package cchat

import "github.com/google/flatbuffers/go"

import (
  context "context"
  grpc "google.golang.org/grpc"
)

// Client API for LabelContainerService service
type LabelContainerServiceClient interface{
  SetLabel(ctx context.Context, in *flatbuffers.Builder, 
  	opts... grpc.CallOption) (* NoReply, error)  
}

type labelContainerServiceClient struct {
  cc *grpc.ClientConn
}

func NewLabelContainerServiceClient(cc *grpc.ClientConn) LabelContainerServiceClient {
  return &labelContainerServiceClient{cc}
}

func (c *labelContainerServiceClient) SetLabel(ctx context.Context, in *flatbuffers.Builder, 
	opts... grpc.CallOption) (* NoReply, error) {
  out := new(NoReply)
  err := grpc.Invoke(ctx, "/cchat.LabelContainerService/SetLabel", in, out, c.cc, opts...)
  if err != nil { return nil, err }
  return out, nil
}

// Server API for LabelContainerService service
type LabelContainerServiceServer interface {
  SetLabel(context.Context, *SetLabelParameters) (*flatbuffers.Builder, error)  
}

func RegisterLabelContainerServiceServer(s *grpc.Server, srv LabelContainerServiceServer) {
  s.RegisterService(&_LabelContainerService_serviceDesc, srv)
}

func _LabelContainerService_SetLabel_Handler(srv interface{}, ctx context.Context,
	dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
  in := new(SetLabelParameters)
  if err := dec(in); err != nil { return nil, err }
  if interceptor == nil { return srv.(LabelContainerServiceServer).SetLabel(ctx, in) }
  info := &grpc.UnaryServerInfo{
    Server: srv,
    FullMethod: "/cchat.LabelContainerService/SetLabel",
  }
  
  handler := func(ctx context.Context, req interface{}) (interface{}, error) {
    return srv.(LabelContainerServiceServer).SetLabel(ctx, req.(* SetLabelParameters))
  }
  return interceptor(ctx, in, info, handler)
}


var _LabelContainerService_serviceDesc = grpc.ServiceDesc{
  ServiceName: "cchat.LabelContainerService",
  HandlerType: (*LabelContainerServiceServer)(nil),
  Methods: []grpc.MethodDesc{
    {
      MethodName: "SetLabel",
      Handler: _LabelContainerService_SetLabel_Handler, 
    },
  },
  Streams: []grpc.StreamDesc{
  },
}

