// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cchat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type LabelContainer struct {
	_tab flatbuffers.Table
}

func GetRootAsLabelContainer(buf []byte, offset flatbuffers.UOffsetT) *LabelContainer {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &LabelContainer{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsLabelContainer(buf []byte, offset flatbuffers.UOffsetT) *LabelContainer {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &LabelContainer{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *LabelContainer) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *LabelContainer) Table() flatbuffers.Table {
	return rcv._tab
}

func LabelContainerStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func LabelContainerEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
