//Generated by gRPC Go plugin
//If you make any local changes, they will be lost
//source: cchat

package cchat

import "github.com/google/flatbuffers/go"

import (
  context "context"
  grpc "google.golang.org/grpc"
)

// Client API for ListerService service
type ListerServiceClient interface{
  Servers(ctx context.Context, in *flatbuffers.Builder, 
  	opts... grpc.CallOption) (* ServersReturns, error)  
}

type listerServiceClient struct {
  cc *grpc.ClientConn
}

func NewListerServiceClient(cc *grpc.ClientConn) ListerServiceClient {
  return &listerServiceClient{cc}
}

func (c *listerServiceClient) Servers(ctx context.Context, in *flatbuffers.Builder, 
	opts... grpc.CallOption) (* ServersReturns, error) {
  out := new(ServersReturns)
  err := grpc.Invoke(ctx, "/cchat.ListerService/Servers", in, out, c.cc, opts...)
  if err != nil { return nil, err }
  return out, nil
}

// Server API for ListerService service
type ListerServiceServer interface {
  Servers(context.Context, *ServersParameters) (*flatbuffers.Builder, error)  
}

func RegisterListerServiceServer(s *grpc.Server, srv ListerServiceServer) {
  s.RegisterService(&_ListerService_serviceDesc, srv)
}

func _ListerService_Servers_Handler(srv interface{}, ctx context.Context,
	dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
  in := new(ServersParameters)
  if err := dec(in); err != nil { return nil, err }
  if interceptor == nil { return srv.(ListerServiceServer).Servers(ctx, in) }
  info := &grpc.UnaryServerInfo{
    Server: srv,
    FullMethod: "/cchat.ListerService/Servers",
  }
  
  handler := func(ctx context.Context, req interface{}) (interface{}, error) {
    return srv.(ListerServiceServer).Servers(ctx, req.(* ServersParameters))
  }
  return interceptor(ctx, in, info, handler)
}


var _ListerService_serviceDesc = grpc.ServiceDesc{
  ServiceName: "cchat.ListerService",
  HandlerType: (*ListerServiceServer)(nil),
  Methods: []grpc.MethodDesc{
    {
      MethodName: "Servers",
      Handler: _ListerService_Servers_Handler, 
    },
  },
  Streams: []grpc.StreamDesc{
  },
}

