// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cchat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Lister struct {
	_tab flatbuffers.Table
}

func GetRootAsLister(buf []byte, offset flatbuffers.UOffsetT) *Lister {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Lister{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsLister(buf []byte, offset flatbuffers.UOffsetT) *Lister {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Lister{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *Lister) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Lister) Table() flatbuffers.Table {
	return rcv._tab
}

func ListerStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func ListerEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
