// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cchat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MemberLister struct {
	_tab flatbuffers.Table
}

func GetRootAsMemberLister(buf []byte, offset flatbuffers.UOffsetT) *MemberLister {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MemberLister{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsMemberLister(buf []byte, offset flatbuffers.UOffsetT) *MemberLister {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MemberLister{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *MemberLister) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MemberLister) Table() flatbuffers.Table {
	return rcv._tab
}

func MemberListerStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func MemberListerEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
