// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cchat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MemberDynamicSection struct {
	_tab flatbuffers.Table
}

func GetRootAsMemberDynamicSection(buf []byte, offset flatbuffers.UOffsetT) *MemberDynamicSection {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MemberDynamicSection{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsMemberDynamicSection(buf []byte, offset flatbuffers.UOffsetT) *MemberDynamicSection {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MemberDynamicSection{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *MemberDynamicSection) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MemberDynamicSection) Table() flatbuffers.Table {
	return rcv._tab
}

func MemberDynamicSectionStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func MemberDynamicSectionEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
