//Generated by gRPC Go plugin
//If you make any local changes, they will be lost
//source: cchat

package cchat

import "github.com/google/flatbuffers/go"

import (
  context "context"
  grpc "google.golang.org/grpc"
)

// Client API for MemberListerService service
type MemberListerServiceClient interface{
  ListMembers(ctx context.Context, in *flatbuffers.Builder, 
  	opts... grpc.CallOption) (* ListMembersReturns, error)  
}

type memberListerServiceClient struct {
  cc *grpc.ClientConn
}

func NewMemberListerServiceClient(cc *grpc.ClientConn) MemberListerServiceClient {
  return &memberListerServiceClient{cc}
}

func (c *memberListerServiceClient) ListMembers(ctx context.Context, in *flatbuffers.Builder, 
	opts... grpc.CallOption) (* ListMembersReturns, error) {
  out := new(ListMembersReturns)
  err := grpc.Invoke(ctx, "/cchat.MemberListerService/ListMembers", in, out, c.cc, opts...)
  if err != nil { return nil, err }
  return out, nil
}

// Server API for MemberListerService service
type MemberListerServiceServer interface {
  ListMembers(context.Context, *ListMembersParameters) (*flatbuffers.Builder, error)  
}

func RegisterMemberListerServiceServer(s *grpc.Server, srv MemberListerServiceServer) {
  s.RegisterService(&_MemberListerService_serviceDesc, srv)
}

func _MemberListerService_ListMembers_Handler(srv interface{}, ctx context.Context,
	dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
  in := new(ListMembersParameters)
  if err := dec(in); err != nil { return nil, err }
  if interceptor == nil { return srv.(MemberListerServiceServer).ListMembers(ctx, in) }
  info := &grpc.UnaryServerInfo{
    Server: srv,
    FullMethod: "/cchat.MemberListerService/ListMembers",
  }
  
  handler := func(ctx context.Context, req interface{}) (interface{}, error) {
    return srv.(MemberListerServiceServer).ListMembers(ctx, req.(* ListMembersParameters))
  }
  return interceptor(ctx, in, info, handler)
}


var _MemberListerService_serviceDesc = grpc.ServiceDesc{
  ServiceName: "cchat.MemberListerService",
  HandlerType: (*MemberListerServiceServer)(nil),
  Methods: []grpc.MethodDesc{
    {
      MethodName: "ListMembers",
      Handler: _MemberListerService_ListMembers_Handler, 
    },
  },
  Streams: []grpc.StreamDesc{
  },
}

