// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cchat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MemberListContainer struct {
	_tab flatbuffers.Table
}

func GetRootAsMemberListContainer(buf []byte, offset flatbuffers.UOffsetT) *MemberListContainer {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MemberListContainer{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsMemberListContainer(buf []byte, offset flatbuffers.UOffsetT) *MemberListContainer {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MemberListContainer{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *MemberListContainer) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MemberListContainer) Table() flatbuffers.Table {
	return rcv._tab
}

func MemberListContainerStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func MemberListContainerEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
