// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cchat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MessagesContainer struct {
	_tab flatbuffers.Table
}

func GetRootAsMessagesContainer(buf []byte, offset flatbuffers.UOffsetT) *MessagesContainer {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MessagesContainer{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsMessagesContainer(buf []byte, offset flatbuffers.UOffsetT) *MessagesContainer {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MessagesContainer{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *MessagesContainer) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MessagesContainer) Table() flatbuffers.Table {
	return rcv._tab
}

func MessagesContainerStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func MessagesContainerEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
