// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cchat

import (
	flatbuffers "github.com/google/flatbuffers/go"

	cchat__core "cchat/core"
)

type MessageDelete struct {
	_tab flatbuffers.Table
}

func GetRootAsMessageDelete(buf []byte, offset flatbuffers.UOffsetT) *MessageDelete {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MessageDelete{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsMessageDelete(buf []byte, offset flatbuffers.UOffsetT) *MessageDelete {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MessageDelete{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *MessageDelete) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MessageDelete) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MessageDelete) Id() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *MessageDelete) Time(obj *cchat__core.Time) *cchat__core.Time {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(cchat__core.Time)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func MessageDeleteStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func MessageDeleteAddId(builder *flatbuffers.Builder, id flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(id), 0)
}
func MessageDeleteAddTime(builder *flatbuffers.Builder, time flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(time), 0)
}
func MessageDeleteEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
