//Generated by gRPC Go plugin
//If you make any local changes, they will be lost
//source: cchat

package cchat

import "github.com/google/flatbuffers/go"

import (
  context "context"
  grpc "google.golang.org/grpc"
)

// Client API for NicknamerService service
type NicknamerServiceClient interface{
  Nickname(ctx context.Context, in *flatbuffers.Builder, 
  	opts... grpc.CallOption) (* NicknameReturns, error)  
}

type nicknamerServiceClient struct {
  cc *grpc.ClientConn
}

func NewNicknamerServiceClient(cc *grpc.ClientConn) NicknamerServiceClient {
  return &nicknamerServiceClient{cc}
}

func (c *nicknamerServiceClient) Nickname(ctx context.Context, in *flatbuffers.Builder, 
	opts... grpc.CallOption) (* NicknameReturns, error) {
  out := new(NicknameReturns)
  err := grpc.Invoke(ctx, "/cchat.NicknamerService/Nickname", in, out, c.cc, opts...)
  if err != nil { return nil, err }
  return out, nil
}

// Server API for NicknamerService service
type NicknamerServiceServer interface {
  Nickname(context.Context, *NicknameParameters) (*flatbuffers.Builder, error)  
}

func RegisterNicknamerServiceServer(s *grpc.Server, srv NicknamerServiceServer) {
  s.RegisterService(&_NicknamerService_serviceDesc, srv)
}

func _NicknamerService_Nickname_Handler(srv interface{}, ctx context.Context,
	dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
  in := new(NicknameParameters)
  if err := dec(in); err != nil { return nil, err }
  if interceptor == nil { return srv.(NicknamerServiceServer).Nickname(ctx, in) }
  info := &grpc.UnaryServerInfo{
    Server: srv,
    FullMethod: "/cchat.NicknamerService/Nickname",
  }
  
  handler := func(ctx context.Context, req interface{}) (interface{}, error) {
    return srv.(NicknamerServiceServer).Nickname(ctx, req.(* NicknameParameters))
  }
  return interceptor(ctx, in, info, handler)
}


var _NicknamerService_serviceDesc = grpc.ServiceDesc{
  ServiceName: "cchat.NicknamerService",
  HandlerType: (*NicknamerServiceServer)(nil),
  Methods: []grpc.MethodDesc{
    {
      MethodName: "Nickname",
      Handler: _NicknamerService_Nickname_Handler, 
    },
  },
  Streams: []grpc.StreamDesc{
  },
}

