// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cchat

import (
	flatbuffers "github.com/google/flatbuffers/go"

	cchat__call "cchat/call"
)

type NicknameParameters struct {
	_tab flatbuffers.Table
}

func GetRootAsNicknameParameters(buf []byte, offset flatbuffers.UOffsetT) *NicknameParameters {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &NicknameParameters{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsNicknameParameters(buf []byte, offset flatbuffers.UOffsetT) *NicknameParameters {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &NicknameParameters{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *NicknameParameters) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *NicknameParameters) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *NicknameParameters) Call(obj *cchat__call.ID) *cchat__call.ID {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(cchat__call.ID)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *NicknameParameters) Ctx(obj *cchat__call.Context) *cchat__call.Context {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(cchat__call.Context)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *NicknameParameters) LabelContainer(obj *LabelContainer) *LabelContainer {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(LabelContainer)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func NicknameParametersStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func NicknameParametersAddCall(builder *flatbuffers.Builder, call flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(call), 0)
}
func NicknameParametersAddCtx(builder *flatbuffers.Builder, ctx flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(ctx), 0)
}
func NicknameParametersAddLabelContainer(builder *flatbuffers.Builder, labelContainer flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(labelContainer), 0)
}
func NicknameParametersEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
