// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cchat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Noncer struct {
	_tab flatbuffers.Table
}

func GetRootAsNoncer(buf []byte, offset flatbuffers.UOffsetT) *Noncer {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Noncer{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsNoncer(buf []byte, offset flatbuffers.UOffsetT) *Noncer {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Noncer{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *Noncer) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Noncer) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Noncer) Nonce() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func NoncerStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func NoncerAddNonce(builder *flatbuffers.Builder, nonce flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(nonce), 0)
}
func NoncerEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
