// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cchat

import (
	flatbuffers "github.com/google/flatbuffers/go"

	cchat__call "cchat/call"
)

type RemoveTyperParameters struct {
	_tab flatbuffers.Table
}

func GetRootAsRemoveTyperParameters(buf []byte, offset flatbuffers.UOffsetT) *RemoveTyperParameters {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RemoveTyperParameters{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsRemoveTyperParameters(buf []byte, offset flatbuffers.UOffsetT) *RemoveTyperParameters {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RemoveTyperParameters{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *RemoveTyperParameters) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RemoveTyperParameters) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RemoveTyperParameters) Call(obj *cchat__call.ID) *cchat__call.ID {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(cchat__call.ID)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *RemoveTyperParameters) TyperId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func RemoveTyperParametersStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func RemoveTyperParametersAddCall(builder *flatbuffers.Builder, call flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(call), 0)
}
func RemoveTyperParametersAddTyperId(builder *flatbuffers.Builder, typerId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(typerId), 0)
}
func RemoveTyperParametersEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
