// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cchat

import (
	flatbuffers "github.com/google/flatbuffers/go"

	cchat__call "cchat/call"
)

type RemoveMemberParameters struct {
	_tab flatbuffers.Table
}

func GetRootAsRemoveMemberParameters(buf []byte, offset flatbuffers.UOffsetT) *RemoveMemberParameters {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RemoveMemberParameters{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsRemoveMemberParameters(buf []byte, offset flatbuffers.UOffsetT) *RemoveMemberParameters {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &RemoveMemberParameters{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *RemoveMemberParameters) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RemoveMemberParameters) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RemoveMemberParameters) Call(obj *cchat__call.ID) *cchat__call.ID {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(cchat__call.ID)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *RemoveMemberParameters) SectionId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *RemoveMemberParameters) MemberId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func RemoveMemberParametersStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func RemoveMemberParametersAddCall(builder *flatbuffers.Builder, call flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(call), 0)
}
func RemoveMemberParametersAddSectionId(builder *flatbuffers.Builder, sectionId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(sectionId), 0)
}
func RemoveMemberParametersAddMemberId(builder *flatbuffers.Builder, memberId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(memberId), 0)
}
func RemoveMemberParametersEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
