// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cchat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Replier struct {
	_tab flatbuffers.Table
}

func GetRootAsReplier(buf []byte, offset flatbuffers.UOffsetT) *Replier {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Replier{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsReplier(buf []byte, offset flatbuffers.UOffsetT) *Replier {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Replier{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *Replier) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Replier) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Replier) ReplyingTo() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ReplierStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ReplierAddReplyingTo(builder *flatbuffers.Builder, replyingTo flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(replyingTo), 0)
}
func ReplierEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
