//Generated by gRPC Go plugin
//If you make any local changes, they will be lost
//source: cchat

package cchat

import "github.com/google/flatbuffers/go"

import (
  context "context"
  grpc "google.golang.org/grpc"
)

// Client API for SenderService service
type SenderServiceClient interface{
  Send(ctx context.Context, in *flatbuffers.Builder, 
  	opts... grpc.CallOption) (* SendReturns, error)  
}

type senderServiceClient struct {
  cc *grpc.ClientConn
}

func NewSenderServiceClient(cc *grpc.ClientConn) SenderServiceClient {
  return &senderServiceClient{cc}
}

func (c *senderServiceClient) Send(ctx context.Context, in *flatbuffers.Builder, 
	opts... grpc.CallOption) (* SendReturns, error) {
  out := new(SendReturns)
  err := grpc.Invoke(ctx, "/cchat.SenderService/Send", in, out, c.cc, opts...)
  if err != nil { return nil, err }
  return out, nil
}

// Server API for SenderService service
type SenderServiceServer interface {
  Send(context.Context, *SendParameters) (*flatbuffers.Builder, error)  
}

func RegisterSenderServiceServer(s *grpc.Server, srv SenderServiceServer) {
  s.RegisterService(&_SenderService_serviceDesc, srv)
}

func _SenderService_Send_Handler(srv interface{}, ctx context.Context,
	dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
  in := new(SendParameters)
  if err := dec(in); err != nil { return nil, err }
  if interceptor == nil { return srv.(SenderServiceServer).Send(ctx, in) }
  info := &grpc.UnaryServerInfo{
    Server: srv,
    FullMethod: "/cchat.SenderService/Send",
  }
  
  handler := func(ctx context.Context, req interface{}) (interface{}, error) {
    return srv.(SenderServiceServer).Send(ctx, req.(* SendParameters))
  }
  return interceptor(ctx, in, info, handler)
}


var _SenderService_serviceDesc = grpc.ServiceDesc{
  ServiceName: "cchat.SenderService",
  HandlerType: (*SenderServiceServer)(nil),
  Methods: []grpc.MethodDesc{
    {
      MethodName: "Send",
      Handler: _SenderService_Send_Handler, 
    },
  },
  Streams: []grpc.StreamDesc{
  },
}

