// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cchat

import (
	flatbuffers "github.com/google/flatbuffers/go"

	cchat__call "cchat/call"
)

type SendParameters struct {
	_tab flatbuffers.Table
}

func GetRootAsSendParameters(buf []byte, offset flatbuffers.UOffsetT) *SendParameters {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SendParameters{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsSendParameters(buf []byte, offset flatbuffers.UOffsetT) *SendParameters {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SendParameters{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *SendParameters) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SendParameters) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SendParameters) Call(obj *cchat__call.ID) *cchat__call.ID {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(cchat__call.ID)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *SendParameters) SendableMessage(obj *SendableMessage) *SendableMessage {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(SendableMessage)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func SendParametersStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func SendParametersAddCall(builder *flatbuffers.Builder, call flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(call), 0)
}
func SendParametersAddSendableMessage(builder *flatbuffers.Builder, sendableMessage flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(sendableMessage), 0)
}
func SendParametersEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
