// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cchat

import (
	flatbuffers "github.com/google/flatbuffers/go"

	cchat__call "cchat/call"
)

type ServersParameters struct {
	_tab flatbuffers.Table
}

func GetRootAsServersParameters(buf []byte, offset flatbuffers.UOffsetT) *ServersParameters {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ServersParameters{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsServersParameters(buf []byte, offset flatbuffers.UOffsetT) *ServersParameters {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ServersParameters{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *ServersParameters) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ServersParameters) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ServersParameters) Call(obj *cchat__call.ID) *cchat__call.ID {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(cchat__call.ID)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *ServersParameters) ServersContainer(obj *ServersContainer) *ServersContainer {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(ServersContainer)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func ServersParametersStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ServersParametersAddCall(builder *flatbuffers.Builder, call flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(call), 0)
}
func ServersParametersAddServersContainer(builder *flatbuffers.Builder, serversContainer flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(serversContainer), 0)
}
func ServersParametersEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
