// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cchat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ServersContainer struct {
	_tab flatbuffers.Table
}

func GetRootAsServersContainer(buf []byte, offset flatbuffers.UOffsetT) *ServersContainer {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ServersContainer{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsServersContainer(buf []byte, offset flatbuffers.UOffsetT) *ServersContainer {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ServersContainer{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *ServersContainer) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ServersContainer) Table() flatbuffers.Table {
	return rcv._tab
}

func ServersContainerStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func ServersContainerEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
