//Generated by gRPC Go plugin
//If you make any local changes, they will be lost
//source: cchat

package cchat

import "github.com/google/flatbuffers/go"

import (
  context "context"
  grpc "google.golang.org/grpc"
)

// Client API for SessionService service
type SessionServiceClient interface{
  Disconnect(ctx context.Context, in *flatbuffers.Builder, 
  	opts... grpc.CallOption) (* DisconnectReturns, error)  
}

type sessionServiceClient struct {
  cc *grpc.ClientConn
}

func NewSessionServiceClient(cc *grpc.ClientConn) SessionServiceClient {
  return &sessionServiceClient{cc}
}

func (c *sessionServiceClient) Disconnect(ctx context.Context, in *flatbuffers.Builder, 
	opts... grpc.CallOption) (* DisconnectReturns, error) {
  out := new(DisconnectReturns)
  err := grpc.Invoke(ctx, "/cchat.SessionService/Disconnect", in, out, c.cc, opts...)
  if err != nil { return nil, err }
  return out, nil
}

// Server API for SessionService service
type SessionServiceServer interface {
  Disconnect(context.Context, *DisconnectParameters) (*flatbuffers.Builder, error)  
}

func RegisterSessionServiceServer(s *grpc.Server, srv SessionServiceServer) {
  s.RegisterService(&_SessionService_serviceDesc, srv)
}

func _SessionService_Disconnect_Handler(srv interface{}, ctx context.Context,
	dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
  in := new(DisconnectParameters)
  if err := dec(in); err != nil { return nil, err }
  if interceptor == nil { return srv.(SessionServiceServer).Disconnect(ctx, in) }
  info := &grpc.UnaryServerInfo{
    Server: srv,
    FullMethod: "/cchat.SessionService/Disconnect",
  }
  
  handler := func(ctx context.Context, req interface{}) (interface{}, error) {
    return srv.(SessionServiceServer).Disconnect(ctx, req.(* DisconnectParameters))
  }
  return interceptor(ctx, in, info, handler)
}


var _SessionService_serviceDesc = grpc.ServiceDesc{
  ServiceName: "cchat.SessionService",
  HandlerType: (*SessionServiceServer)(nil),
  Methods: []grpc.MethodDesc{
    {
      MethodName: "Disconnect",
      Handler: _SessionService_Disconnect_Handler, 
    },
  },
  Streams: []grpc.StreamDesc{
  },
}

