// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cchat

import (
	flatbuffers "github.com/google/flatbuffers/go"

	cchat__core "cchat/core"
)

type SessionSaver struct {
	_tab flatbuffers.Table
}

func GetRootAsSessionSaver(buf []byte, offset flatbuffers.UOffsetT) *SessionSaver {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SessionSaver{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsSessionSaver(buf []byte, offset flatbuffers.UOffsetT) *SessionSaver {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SessionSaver{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *SessionSaver) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SessionSaver) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SessionSaver) SaveSession(obj *cchat__core.StringPair) *cchat__core.StringPair {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(cchat__core.StringPair)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func SessionSaverStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func SessionSaverAddSaveSession(builder *flatbuffers.Builder, saveSession flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(saveSession), 0)
}
func SessionSaverEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
