//Generated by gRPC Go plugin
//If you make any local changes, they will be lost
//source: cchat

package cchat

import "github.com/google/flatbuffers/go"

import (
  context "context"
  grpc "google.golang.org/grpc"
)

// Client API for SessionRestorerService service
type SessionRestorerServiceClient interface{
  RestoreSession(ctx context.Context, in *flatbuffers.Builder, 
  	opts... grpc.CallOption) (* RestoreSessionReturns, error)  
}

type sessionRestorerServiceClient struct {
  cc *grpc.ClientConn
}

func NewSessionRestorerServiceClient(cc *grpc.ClientConn) SessionRestorerServiceClient {
  return &sessionRestorerServiceClient{cc}
}

func (c *sessionRestorerServiceClient) RestoreSession(ctx context.Context, in *flatbuffers.Builder, 
	opts... grpc.CallOption) (* RestoreSessionReturns, error) {
  out := new(RestoreSessionReturns)
  err := grpc.Invoke(ctx, "/cchat.SessionRestorerService/RestoreSession", in, out, c.cc, opts...)
  if err != nil { return nil, err }
  return out, nil
}

// Server API for SessionRestorerService service
type SessionRestorerServiceServer interface {
  RestoreSession(context.Context, *RestoreSessionParameters) (*flatbuffers.Builder, error)  
}

func RegisterSessionRestorerServiceServer(s *grpc.Server, srv SessionRestorerServiceServer) {
  s.RegisterService(&_SessionRestorerService_serviceDesc, srv)
}

func _SessionRestorerService_RestoreSession_Handler(srv interface{}, ctx context.Context,
	dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
  in := new(RestoreSessionParameters)
  if err := dec(in); err != nil { return nil, err }
  if interceptor == nil { return srv.(SessionRestorerServiceServer).RestoreSession(ctx, in) }
  info := &grpc.UnaryServerInfo{
    Server: srv,
    FullMethod: "/cchat.SessionRestorerService/RestoreSession",
  }
  
  handler := func(ctx context.Context, req interface{}) (interface{}, error) {
    return srv.(SessionRestorerServiceServer).RestoreSession(ctx, req.(* RestoreSessionParameters))
  }
  return interceptor(ctx, in, info, handler)
}


var _SessionRestorerService_serviceDesc = grpc.ServiceDesc{
  ServiceName: "cchat.SessionRestorerService",
  HandlerType: (*SessionRestorerServiceServer)(nil),
  Methods: []grpc.MethodDesc{
    {
      MethodName: "RestoreSession",
      Handler: _SessionRestorerService_RestoreSession_Handler, 
    },
  },
  Streams: []grpc.StreamDesc{
  },
}

