// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cchat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SessionRestorer struct {
	_tab flatbuffers.Table
}

func GetRootAsSessionRestorer(buf []byte, offset flatbuffers.UOffsetT) *SessionRestorer {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SessionRestorer{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsSessionRestorer(buf []byte, offset flatbuffers.UOffsetT) *SessionRestorer {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SessionRestorer{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *SessionRestorer) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SessionRestorer) Table() flatbuffers.Table {
	return rcv._tab
}

func SessionRestorerStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func SessionRestorerEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
