// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cchat

import (
	flatbuffers "github.com/google/flatbuffers/go"

	cchat__call "cchat/call"
	cchat__text "cchat/text"
)

type SetLabelParameters struct {
	_tab flatbuffers.Table
}

func GetRootAsSetLabelParameters(buf []byte, offset flatbuffers.UOffsetT) *SetLabelParameters {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SetLabelParameters{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsSetLabelParameters(buf []byte, offset flatbuffers.UOffsetT) *SetLabelParameters {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SetLabelParameters{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *SetLabelParameters) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SetLabelParameters) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SetLabelParameters) Call(obj *cchat__call.ID) *cchat__call.ID {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(cchat__call.ID)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *SetLabelParameters) Rich(obj *cchat__text.Rich) *cchat__text.Rich {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(cchat__text.Rich)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func SetLabelParametersStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func SetLabelParametersAddCall(builder *flatbuffers.Builder, call flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(call), 0)
}
func SetLabelParametersAddRich(builder *flatbuffers.Builder, rich flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(rich), 0)
}
func SetLabelParametersEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
