// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cchat

import (
	flatbuffers "github.com/google/flatbuffers/go"

	cchat__call "cchat/call"
)

type SetMemberParameters struct {
	_tab flatbuffers.Table
}

func GetRootAsSetMemberParameters(buf []byte, offset flatbuffers.UOffsetT) *SetMemberParameters {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SetMemberParameters{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsSetMemberParameters(buf []byte, offset flatbuffers.UOffsetT) *SetMemberParameters {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SetMemberParameters{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *SetMemberParameters) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SetMemberParameters) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SetMemberParameters) Call(obj *cchat__call.ID) *cchat__call.ID {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(cchat__call.ID)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *SetMemberParameters) SectionId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *SetMemberParameters) Member(obj *ListMember) *ListMember {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(ListMember)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func SetMemberParametersStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func SetMemberParametersAddCall(builder *flatbuffers.Builder, call flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(call), 0)
}
func SetMemberParametersAddSectionId(builder *flatbuffers.Builder, sectionId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(sectionId), 0)
}
func SetMemberParametersAddMember(builder *flatbuffers.Builder, member flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(member), 0)
}
func SetMemberParametersEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
