// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cchat

import (
	flatbuffers "github.com/google/flatbuffers/go"

	cchat__call "cchat/call"
)

type SetUnreadParameters struct {
	_tab flatbuffers.Table
}

func GetRootAsSetUnreadParameters(buf []byte, offset flatbuffers.UOffsetT) *SetUnreadParameters {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SetUnreadParameters{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsSetUnreadParameters(buf []byte, offset flatbuffers.UOffsetT) *SetUnreadParameters {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SetUnreadParameters{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *SetUnreadParameters) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SetUnreadParameters) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SetUnreadParameters) Call(obj *cchat__call.ID) *cchat__call.ID {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(cchat__call.ID)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *SetUnreadParameters) Unread() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *SetUnreadParameters) MutateUnread(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func (rcv *SetUnreadParameters) Mentioned() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *SetUnreadParameters) MutateMentioned(n bool) bool {
	return rcv._tab.MutateBoolSlot(8, n)
}

func SetUnreadParametersStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func SetUnreadParametersAddCall(builder *flatbuffers.Builder, call flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(call), 0)
}
func SetUnreadParametersAddUnread(builder *flatbuffers.Builder, unread bool) {
	builder.PrependBoolSlot(1, unread, false)
}
func SetUnreadParametersAddMentioned(builder *flatbuffers.Builder, mentioned bool) {
	builder.PrependBoolSlot(2, mentioned, false)
}
func SetUnreadParametersEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
