//Generated by gRPC Go plugin
//If you make any local changes, they will be lost
//source: cchat

package cchat

import "github.com/google/flatbuffers/go"

import (
  context "context"
  grpc "google.golang.org/grpc"
)

// Client API for TypingContainerService service
type TypingContainerServiceClient interface{
  AddTyper(ctx context.Context, in *flatbuffers.Builder, 
  	opts... grpc.CallOption) (* NoReply, error)  
  RemoveTyper(ctx context.Context, in *flatbuffers.Builder, 
  	opts... grpc.CallOption) (* NoReply, error)  
}

type typingContainerServiceClient struct {
  cc *grpc.ClientConn
}

func NewTypingContainerServiceClient(cc *grpc.ClientConn) TypingContainerServiceClient {
  return &typingContainerServiceClient{cc}
}

func (c *typingContainerServiceClient) AddTyper(ctx context.Context, in *flatbuffers.Builder, 
	opts... grpc.CallOption) (* NoReply, error) {
  out := new(NoReply)
  err := grpc.Invoke(ctx, "/cchat.TypingContainerService/AddTyper", in, out, c.cc, opts...)
  if err != nil { return nil, err }
  return out, nil
}

func (c *typingContainerServiceClient) RemoveTyper(ctx context.Context, in *flatbuffers.Builder, 
	opts... grpc.CallOption) (* NoReply, error) {
  out := new(NoReply)
  err := grpc.Invoke(ctx, "/cchat.TypingContainerService/RemoveTyper", in, out, c.cc, opts...)
  if err != nil { return nil, err }
  return out, nil
}

// Server API for TypingContainerService service
type TypingContainerServiceServer interface {
  AddTyper(context.Context, *AddTyperParameters) (*flatbuffers.Builder, error)  
  RemoveTyper(context.Context, *RemoveTyperParameters) (*flatbuffers.Builder, error)  
}

func RegisterTypingContainerServiceServer(s *grpc.Server, srv TypingContainerServiceServer) {
  s.RegisterService(&_TypingContainerService_serviceDesc, srv)
}

func _TypingContainerService_AddTyper_Handler(srv interface{}, ctx context.Context,
	dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
  in := new(AddTyperParameters)
  if err := dec(in); err != nil { return nil, err }
  if interceptor == nil { return srv.(TypingContainerServiceServer).AddTyper(ctx, in) }
  info := &grpc.UnaryServerInfo{
    Server: srv,
    FullMethod: "/cchat.TypingContainerService/AddTyper",
  }
  
  handler := func(ctx context.Context, req interface{}) (interface{}, error) {
    return srv.(TypingContainerServiceServer).AddTyper(ctx, req.(* AddTyperParameters))
  }
  return interceptor(ctx, in, info, handler)
}


func _TypingContainerService_RemoveTyper_Handler(srv interface{}, ctx context.Context,
	dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
  in := new(RemoveTyperParameters)
  if err := dec(in); err != nil { return nil, err }
  if interceptor == nil { return srv.(TypingContainerServiceServer).RemoveTyper(ctx, in) }
  info := &grpc.UnaryServerInfo{
    Server: srv,
    FullMethod: "/cchat.TypingContainerService/RemoveTyper",
  }
  
  handler := func(ctx context.Context, req interface{}) (interface{}, error) {
    return srv.(TypingContainerServiceServer).RemoveTyper(ctx, req.(* RemoveTyperParameters))
  }
  return interceptor(ctx, in, info, handler)
}


var _TypingContainerService_serviceDesc = grpc.ServiceDesc{
  ServiceName: "cchat.TypingContainerService",
  HandlerType: (*TypingContainerServiceServer)(nil),
  Methods: []grpc.MethodDesc{
    {
      MethodName: "AddTyper",
      Handler: _TypingContainerService_AddTyper_Handler, 
    },
    {
      MethodName: "RemoveTyper",
      Handler: _TypingContainerService_RemoveTyper_Handler, 
    },
  },
  Streams: []grpc.StreamDesc{
  },
}

