// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cchat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TypingIndicator struct {
	_tab flatbuffers.Table
}

func GetRootAsTypingIndicator(buf []byte, offset flatbuffers.UOffsetT) *TypingIndicator {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TypingIndicator{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsTypingIndicator(buf []byte, offset flatbuffers.UOffsetT) *TypingIndicator {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TypingIndicator{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *TypingIndicator) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TypingIndicator) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *TypingIndicator) TypingTimeout() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *TypingIndicator) MutateTypingTimeout(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func TypingIndicatorStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func TypingIndicatorAddTypingTimeout(builder *flatbuffers.Builder, typingTimeout int64) {
	builder.PrependInt64Slot(0, typingTimeout, 0)
}
func TypingIndicatorEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
