// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cchat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type TypingContainer struct {
	_tab flatbuffers.Table
}

func GetRootAsTypingContainer(buf []byte, offset flatbuffers.UOffsetT) *TypingContainer {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &TypingContainer{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsTypingContainer(buf []byte, offset flatbuffers.UOffsetT) *TypingContainer {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &TypingContainer{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *TypingContainer) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *TypingContainer) Table() flatbuffers.Table {
	return rcv._tab
}

func TypingContainerStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func TypingContainerEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
