// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cchat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type UnreadIndicator struct {
	_tab flatbuffers.Table
}

func GetRootAsUnreadIndicator(buf []byte, offset flatbuffers.UOffsetT) *UnreadIndicator {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &UnreadIndicator{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsUnreadIndicator(buf []byte, offset flatbuffers.UOffsetT) *UnreadIndicator {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &UnreadIndicator{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *UnreadIndicator) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *UnreadIndicator) Table() flatbuffers.Table {
	return rcv._tab
}

func UnreadIndicatorStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func UnreadIndicatorEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
