//Generated by gRPC Go plugin
//If you make any local changes, they will be lost
//source: cchat

package cchat

import "github.com/google/flatbuffers/go"

import (
  context "context"
  grpc "google.golang.org/grpc"
)

// Client API for UnreadIndicatorService service
type UnreadIndicatorServiceClient interface{
  UnreadIndicate(ctx context.Context, in *flatbuffers.Builder, 
  	opts... grpc.CallOption) (* UnreadIndicateReturns, error)  
}

type unreadIndicatorServiceClient struct {
  cc *grpc.ClientConn
}

func NewUnreadIndicatorServiceClient(cc *grpc.ClientConn) UnreadIndicatorServiceClient {
  return &unreadIndicatorServiceClient{cc}
}

func (c *unreadIndicatorServiceClient) UnreadIndicate(ctx context.Context, in *flatbuffers.Builder, 
	opts... grpc.CallOption) (* UnreadIndicateReturns, error) {
  out := new(UnreadIndicateReturns)
  err := grpc.Invoke(ctx, "/cchat.UnreadIndicatorService/UnreadIndicate", in, out, c.cc, opts...)
  if err != nil { return nil, err }
  return out, nil
}

// Server API for UnreadIndicatorService service
type UnreadIndicatorServiceServer interface {
  UnreadIndicate(context.Context, *UnreadIndicateParameters) (*flatbuffers.Builder, error)  
}

func RegisterUnreadIndicatorServiceServer(s *grpc.Server, srv UnreadIndicatorServiceServer) {
  s.RegisterService(&_UnreadIndicatorService_serviceDesc, srv)
}

func _UnreadIndicatorService_UnreadIndicate_Handler(srv interface{}, ctx context.Context,
	dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
  in := new(UnreadIndicateParameters)
  if err := dec(in); err != nil { return nil, err }
  if interceptor == nil { return srv.(UnreadIndicatorServiceServer).UnreadIndicate(ctx, in) }
  info := &grpc.UnaryServerInfo{
    Server: srv,
    FullMethod: "/cchat.UnreadIndicatorService/UnreadIndicate",
  }
  
  handler := func(ctx context.Context, req interface{}) (interface{}, error) {
    return srv.(UnreadIndicatorServiceServer).UnreadIndicate(ctx, req.(* UnreadIndicateParameters))
  }
  return interceptor(ctx, in, info, handler)
}


var _UnreadIndicatorService_serviceDesc = grpc.ServiceDesc{
  ServiceName: "cchat.UnreadIndicatorService",
  HandlerType: (*UnreadIndicatorServiceServer)(nil),
  Methods: []grpc.MethodDesc{
    {
      MethodName: "UnreadIndicate",
      Handler: _UnreadIndicatorService_UnreadIndicate_Handler, 
    },
  },
  Streams: []grpc.StreamDesc{
  },
}

