//Generated by gRPC Go plugin
//If you make any local changes, they will be lost
//source: cchat

package cchat

import "github.com/google/flatbuffers/go"

import (
  context "context"
  grpc "google.golang.org/grpc"
)

// Client API for UnreadContainerService service
type UnreadContainerServiceClient interface{
  SetUnread(ctx context.Context, in *flatbuffers.Builder, 
  	opts... grpc.CallOption) (* NoReply, error)  
}

type unreadContainerServiceClient struct {
  cc *grpc.ClientConn
}

func NewUnreadContainerServiceClient(cc *grpc.ClientConn) UnreadContainerServiceClient {
  return &unreadContainerServiceClient{cc}
}

func (c *unreadContainerServiceClient) SetUnread(ctx context.Context, in *flatbuffers.Builder, 
	opts... grpc.CallOption) (* NoReply, error) {
  out := new(NoReply)
  err := grpc.Invoke(ctx, "/cchat.UnreadContainerService/SetUnread", in, out, c.cc, opts...)
  if err != nil { return nil, err }
  return out, nil
}

// Server API for UnreadContainerService service
type UnreadContainerServiceServer interface {
  SetUnread(context.Context, *SetUnreadParameters) (*flatbuffers.Builder, error)  
}

func RegisterUnreadContainerServiceServer(s *grpc.Server, srv UnreadContainerServiceServer) {
  s.RegisterService(&_UnreadContainerService_serviceDesc, srv)
}

func _UnreadContainerService_SetUnread_Handler(srv interface{}, ctx context.Context,
	dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
  in := new(SetUnreadParameters)
  if err := dec(in); err != nil { return nil, err }
  if interceptor == nil { return srv.(UnreadContainerServiceServer).SetUnread(ctx, in) }
  info := &grpc.UnaryServerInfo{
    Server: srv,
    FullMethod: "/cchat.UnreadContainerService/SetUnread",
  }
  
  handler := func(ctx context.Context, req interface{}) (interface{}, error) {
    return srv.(UnreadContainerServiceServer).SetUnread(ctx, req.(* SetUnreadParameters))
  }
  return interceptor(ctx, in, info, handler)
}


var _UnreadContainerService_serviceDesc = grpc.ServiceDesc{
  ServiceName: "cchat.UnreadContainerService",
  HandlerType: (*UnreadContainerServiceServer)(nil),
  Methods: []grpc.MethodDesc{
    {
      MethodName: "SetUnread",
      Handler: _UnreadContainerService_SetUnread_Handler, 
    },
  },
  Streams: []grpc.StreamDesc{
  },
}

