// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cchat

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type UnreadContainer struct {
	_tab flatbuffers.Table
}

func GetRootAsUnreadContainer(buf []byte, offset flatbuffers.UOffsetT) *UnreadContainer {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &UnreadContainer{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsUnreadContainer(buf []byte, offset flatbuffers.UOffsetT) *UnreadContainer {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &UnreadContainer{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *UnreadContainer) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *UnreadContainer) Table() flatbuffers.Table {
	return rcv._tab
}

func UnreadContainerStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func UnreadContainerEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
