// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package cchat

import (
	flatbuffers "github.com/google/flatbuffers/go"

	cchat__call "cchat/call"
)

type UpdateMessageParameters struct {
	_tab flatbuffers.Table
}

func GetRootAsUpdateMessageParameters(buf []byte, offset flatbuffers.UOffsetT) *UpdateMessageParameters {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &UpdateMessageParameters{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsUpdateMessageParameters(buf []byte, offset flatbuffers.UOffsetT) *UpdateMessageParameters {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &UpdateMessageParameters{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *UpdateMessageParameters) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *UpdateMessageParameters) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *UpdateMessageParameters) Call(obj *cchat__call.ID) *cchat__call.ID {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(cchat__call.ID)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *UpdateMessageParameters) MessageUpdate(obj *MessageUpdate) *MessageUpdate {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(MessageUpdate)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func UpdateMessageParametersStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func UpdateMessageParametersAddCall(builder *flatbuffers.Builder, call flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(call), 0)
}
func UpdateMessageParametersAddMessageUpdate(builder *flatbuffers.Builder, messageUpdate flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(messageUpdate), 0)
}
func UpdateMessageParametersEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
