// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package text

import "strconv"

type Attribute uint32

const (
	AttributeNormal        Attribute = 1
	AttributeBold          Attribute = 2
	AttributeItalics       Attribute = 4
	AttributeUnderline     Attribute = 8
	AttributeStrikethrough Attribute = 16
	AttributeSpoiler       Attribute = 32
	AttributeMonospace     Attribute = 64
	AttributeDimmed        Attribute = 128
)

var EnumNamesAttribute = map[Attribute]string{
	AttributeNormal:        "Normal",
	AttributeBold:          "Bold",
	AttributeItalics:       "Italics",
	AttributeUnderline:     "Underline",
	AttributeStrikethrough: "Strikethrough",
	AttributeSpoiler:       "Spoiler",
	AttributeMonospace:     "Monospace",
	AttributeDimmed:        "Dimmed",
}

var EnumValuesAttribute = map[string]Attribute{
	"Normal":        AttributeNormal,
	"Bold":          AttributeBold,
	"Italics":       AttributeItalics,
	"Underline":     AttributeUnderline,
	"Strikethrough": AttributeStrikethrough,
	"Spoiler":       AttributeSpoiler,
	"Monospace":     AttributeMonospace,
	"Dimmed":        AttributeDimmed,
}

func (v Attribute) String() string {
	if s, ok := EnumNamesAttribute[v]; ok {
		return s
	}
	return "Attribute(" + strconv.FormatInt(int64(v), 10) + ")"
}
