// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package text

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Codeblocker struct {
	_tab flatbuffers.Table
}

func GetRootAsCodeblocker(buf []byte, offset flatbuffers.UOffsetT) *Codeblocker {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Codeblocker{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsCodeblocker(buf []byte, offset flatbuffers.UOffsetT) *Codeblocker {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Codeblocker{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *Codeblocker) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Codeblocker) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Codeblocker) CodeblockLanguage() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func CodeblockerStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func CodeblockerAddCodeblockLanguage(builder *flatbuffers.Builder, codeblockLanguage flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(codeblockLanguage), 0)
}
func CodeblockerEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
