// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package text

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Colorer struct {
	_tab flatbuffers.Table
}

func GetRootAsColorer(buf []byte, offset flatbuffers.UOffsetT) *Colorer {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Colorer{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsColorer(buf []byte, offset flatbuffers.UOffsetT) *Colorer {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Colorer{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *Colorer) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Colorer) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Colorer) Color() uint32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Colorer) MutateColor(n uint32) bool {
	return rcv._tab.MutateUint32Slot(4, n)
}

func ColorerStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ColorerAddColor(builder *flatbuffers.Builder, color uint32) {
	builder.PrependUint32Slot(0, color, 0)
}
func ColorerEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
