// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package text

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ImagerImageSize struct {
	_tab flatbuffers.Table
}

func GetRootAsImagerImageSize(buf []byte, offset flatbuffers.UOffsetT) *ImagerImageSize {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ImagerImageSize{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsImagerImageSize(buf []byte, offset flatbuffers.UOffsetT) *ImagerImageSize {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ImagerImageSize{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *ImagerImageSize) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ImagerImageSize) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ImagerImageSize) W() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ImagerImageSize) MutateW(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *ImagerImageSize) H() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ImagerImageSize) MutateH(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func ImagerImageSizeStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ImagerImageSizeAddW(builder *flatbuffers.Builder, w int32) {
	builder.PrependInt32Slot(0, w, 0)
}
func ImagerImageSizeAddH(builder *flatbuffers.Builder, h int32) {
	builder.PrependInt32Slot(1, h, 0)
}
func ImagerImageSizeEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
