// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package text

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Mentioner struct {
	_tab flatbuffers.Table
}

func GetRootAsMentioner(buf []byte, offset flatbuffers.UOffsetT) *Mentioner {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Mentioner{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsMentioner(buf []byte, offset flatbuffers.UOffsetT) *Mentioner {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Mentioner{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *Mentioner) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Mentioner) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Mentioner) MentionInfo(obj *Rich) *Rich {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(Rich)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func MentionerStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func MentionerAddMentionInfo(builder *flatbuffers.Builder, mentionInfo flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(mentionInfo), 0)
}
func MentionerEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
