// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package text

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type MessageReferencer struct {
	_tab flatbuffers.Table
}

func GetRootAsMessageReferencer(buf []byte, offset flatbuffers.UOffsetT) *MessageReferencer {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &MessageReferencer{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsMessageReferencer(buf []byte, offset flatbuffers.UOffsetT) *MessageReferencer {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &MessageReferencer{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *MessageReferencer) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *MessageReferencer) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *MessageReferencer) MessageId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func MessageReferencerStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func MessageReferencerAddMessageId(builder *flatbuffers.Builder, messageId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(messageId), 0)
}
func MessageReferencerEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
