// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package text

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SegmentBounds struct {
	_tab flatbuffers.Table
}

func GetRootAsSegmentBounds(buf []byte, offset flatbuffers.UOffsetT) *SegmentBounds {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SegmentBounds{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsSegmentBounds(buf []byte, offset flatbuffers.UOffsetT) *SegmentBounds {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &SegmentBounds{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *SegmentBounds) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SegmentBounds) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SegmentBounds) Start() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SegmentBounds) MutateStart(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *SegmentBounds) End() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *SegmentBounds) MutateEnd(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func SegmentBoundsStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func SegmentBoundsAddStart(builder *flatbuffers.Builder, start int32) {
	builder.PrependInt32Slot(0, start, 0)
}
func SegmentBoundsAddEnd(builder *flatbuffers.Builder, end int32) {
	builder.PrependInt32Slot(1, end, 0)
}
func SegmentBoundsEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
