// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package core

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Object struct {
	_tab flatbuffers.Struct
}

func (rcv *Object) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Object) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *Object) ObjectId() uint64 {
	return rcv._tab.GetUint64(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *Object) MutateObjectId(n uint64) bool {
	return rcv._tab.MutateUint64(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func CreateObject(builder *flatbuffers.Builder, objectId uint64) flatbuffers.UOffsetT {
	builder.Prep(8, 8)
	builder.PrependUint64(objectId)
	return builder.Offset()
}
