// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package core

import "strconv"

type Reader byte

const (
	ReaderNONE   Reader = 0
	ReaderStream Reader = 1
	ReaderFile   Reader = 2
)

var EnumNamesReader = map[Reader]string{
	ReaderNONE:   "NONE",
	ReaderStream: "Stream",
	ReaderFile:   "File",
}

var EnumValuesReader = map[string]Reader{
	"NONE":   ReaderNONE,
	"Stream": ReaderStream,
	"File":   ReaderFile,
}

func (v Reader) String() string {
	if s, ok := EnumNamesReader[v]; ok {
		return s
	}
	return "Reader(" + strconv.FormatInt(int64(v), 10) + ")"
}
