// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package core

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Stream struct {
	_tab flatbuffers.Table
}

func GetRootAsStream(buf []byte, offset flatbuffers.UOffsetT) *Stream {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Stream{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsStream(buf []byte, offset flatbuffers.UOffsetT) *Stream {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Stream{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *Stream) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Stream) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Stream) Ticket(obj *StreamTicket) *StreamTicket {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(StreamTicket)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func (rcv *Stream) BufferSize() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Stream) MutateBufferSize(n int64) bool {
	return rcv._tab.MutateInt64Slot(6, n)
}

func StreamStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func StreamAddTicket(builder *flatbuffers.Builder, ticket flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(ticket), 0)
}
func StreamAddBufferSize(builder *flatbuffers.Builder, bufferSize int64) {
	builder.PrependInt64Slot(1, bufferSize, 0)
}
func StreamEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
