// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package core

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type StreamTicket struct {
	_tab flatbuffers.Table
}

func GetRootAsStreamTicket(buf []byte, offset flatbuffers.UOffsetT) *StreamTicket {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StreamTicket{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsStreamTicket(buf []byte, offset flatbuffers.UOffsetT) *StreamTicket {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &StreamTicket{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *StreamTicket) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StreamTicket) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StreamTicket) TicketId() uint64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetUint64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *StreamTicket) MutateTicketId(n uint64) bool {
	return rcv._tab.MutateUint64Slot(4, n)
}

func StreamTicketStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func StreamTicketAddTicketId(builder *flatbuffers.Builder, ticketId uint64) {
	builder.PrependUint64Slot(0, ticketId, 0)
}
func StreamTicketEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
