// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package core

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Time struct {
	_tab flatbuffers.Table
}

func GetRootAsTime(buf []byte, offset flatbuffers.UOffsetT) *Time {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Time{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsTime(buf []byte, offset flatbuffers.UOffsetT) *Time {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Time{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *Time) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Time) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Time) UnixNano() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Time) MutateUnixNano(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func TimeStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func TimeAddUnixNano(builder *flatbuffers.Builder, unixNano int64) {
	builder.PrependInt64Slot(0, unixNano, 0)
}
func TimeEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
